### ISSUE TITLE
Cluster support

### ISSUE THREAD

**Issue by VincentdeWit94** [cakephp/queue#133]
Hi all,

We are trying to implement the cakephp queue with predis.
Is there a way to connect to a redis cluster? Now when we are trying to connect we get a error message about the crosslot not matching (crossslot keys in request don't hash to the same slot).

Thanks!

**Comment by markstory** [comment]
I don't think redis-cluster is supported as [enqueue-redis](https://php-enqueue.github.io/transport/redis/) (the library we use to provide queuing abstractions) doesn't have any easy to find examples of redis cluster.

**Comment by ajibarra** [comment]
@VincentdeWit94 I do not think is possible. CakePHP Queue uses enqueue/simple-client to connect to engines and process jobs which was created specifically to remove all the low-level stuff you dont usually need. The thing is that SimpleClient uses ConnectionFactory to determine the engine based on DSN and it does not accept the Redis object directly. So php-enqueue and enqueue-redis do support Redis Cluster but there is no way to configure it using SimpleClient. Just as a reference, here is how to configure Redis Cluster using RedisConnectionFactory directly:

* https://php-enqueue.github.io/transport/redis/#create-context (see section "With PRedis and custom options:")

```
<?php
use Enqueue\Redis\RedisConnectionFactory;
use Enqueue\Redis\PRedis;

$config = [
    ...
];

$redis = new PRedis($config);

$factory = new RedisConnectionFactory($redis);
```

If you need help configuring your cluster in PRedis:

https://github.com/predis/predis#cluster

**Comment by dereuromark** [comment]
Can we closed then?
