### ISSUE TITLE
Email transport configuration inconsistency

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/queue#135]
Docs states that queue transport should be configured like so:

```php
    'EmailTransport' => [
        'queue' => [
            'className' => QueueTransport::class,
            // The transport to use inside the queue job.
            'transport' => MailTransport::class,
            'config' => [
                // Configuration for MailTransport.
            ]
        ]
    ],
```

Wheras in fact the whole `queue` array is passed to the transport constructor:

https://github.com/cakephp/queue/blob/c073121a4c9e0c1db3f5e75bcf5ca24dafde07b3/src/Mailer/Transport/QueueTransport.php#L87-L89

I'd like to fix that the example from docs would work while keeping the existing behavior. For example pass the `config` array if the key exists and fallback to the whole array thing otherwise.

```php
    protected function prepareData(Message $message): array
    {
        return [
            'transport' => $this->getConfig('transport'),
            'config' => is_array($this->getConfig('config')) ? $this->getConfig('config') : $this->getConfig(),
            'emailMessage' => json_encode($message),
        ];
    }
```

Also it would be great if you could pass just the name of an already configurated transport, for example:

```php
return [
    // ... other configuration
    'EmailTransport' => [
        'default' => [
            'url' => env('EMAIL_URL'),
        ],
        'queue' => [
            'className' => QueueTransport::class,
            // The transport to use inside the queue job.
            'transport' => 'default',
        ]
    ],
];
```

I can provide a PR if that sounds reasonable.

**Comment by markstory** [comment]
> Also it would be great if you could pass just the name of an already configurated transport, for example:

This sounds like a great improvement as configuration can be consolidated.
