### ISSUE TITLE
Documentation in CakePHP Cookbook not found

### ISSUE THREAD

**Issue by ravage84** [cakephp/queue#24]
The documentation metnioned in the [Documentation section](https://github.com/cakephp/queue/blob/0e3a2c147d3b8211bc54a0aa8a0774534331849a/README.md#documentation) leads to [a 404](https://book.cakephp.org/queue/1/).

Also, the documentation cannot be found when searching for it from within the [CakePHP Cookbook](https://book.cakephp.org/4/en/search.html?check_keywords=yes&area=default&q=queue).

**Comment by markstory** [comment]
I don't think we've gotten around to automating the deployment of this documentation just yet.

**Comment by ADmad** [comment]
The plugin docs are deployed and the README link works now.
