### ISSUE TITLE
Shall we add it to packagist?

### ISSUE THREAD

**Issue by steinkel** [cakephp/queue#39]
I see the webhook is not setup yet...

Thanks,

**Comment by ADmad** [comment]
I guess we can, I don't think we are going to change the composer package name `cakephp/queue`.

**Comment by markstory** [comment]
> I guess we can, I don't think we are going to change the composer package name cakephp/queue.

Yea based on #9 we won't be renaming.

**Comment by ADmad** [comment]
https://packagist.org/packages/cakephp/queue
