### ISSUE TITLE
Cannot specify queue other than default

### ISSUE THREAD

**Issue by toggenation** [cakephp/queue#58]
I am using the beanstalk: transport. If I specify a custom config Queue.beanstalkd.* as below this has no effect on the tube / job queue created in beanstalk when I specify the [ 'config' => 'beanstalk' ] options to ->push on a QueueManager or Queue enabled Mailer instance

![image](https://user-images.githubusercontent.com/4483692/117101008-975d6480-adb8-11eb-9884-eb41a30ed5ec.png)

```
 'Queue' => [
        'default' => [
            // A DSN for your configured backend. default: null
            'url' => 'beanstalk:',

            // The queue that will be used for sending messages. default: default
            // This can be overriden when queuing or processing messages
            'queue' => 'default',

            // The name of a configured logger, default: null
            'logger' => null,

            // The name of an event listener class to associate with the worker
            'listener' => \App\Listener\WorkerListener::class,
        ],
        'beanstalk' => [

            // A DSN for your configured backend. default: null
            'url' => 'beanstalk:',

            // The queue that will be used for sending messages. default: default
            // This can be overriden when queuing or processing messages
            'queue' => 'tube1',

            // The name of a configured logger, default: null
            'logger' => 'stdout',

            // The name of an event listener class to associate with the worker
            'listener' => \App\Listener\WorkerListener::class,
        ],
    ],
```

I think this is because SimpleClient is instantiated with only $url = "beanstalk:"

```
//vendor/cakephp/queue/src/Command/WorkerCommand.php
$url = Configure::read(sprintf('Queue.%s.url', $config));
$client = new SimpleClient($url, $logger);
        /** @psalm-suppress InvalidArgument */
$client->bindTopic((string)$args->getOption('queue'), $processor, $args->getOption('processor'));

//  vendor/cakephp/queue/src/QueueManager.php

static::$_clients[$name] = new SimpleClient($config['url'], $logger);
```

I have tested it with passing a configuration array to each instantiation of SimpleClient and it creates the custom queue.

![image](https://user-images.githubusercontent.com/4483692/117102864-87478400-adbc-11eb-9b72-973a1bf7aa58.png)

```
$testConfig = [
        'transport' => 'beanstalk:',
        'client' =>
        [
            'prefix'                   => 'enqueue',
            'separator'                => '.',
            'app_name'                 => 'app',
            'router_topic'             => 'q1',
            'router_queue'             => 'q1',
            'default_queue'            => 'q1',
        ],
        'extensions' => [
            'signal_extension' => false,
            'reply_extension' => false,
        ]
    ];

//vendor/cakephp/queue/src/Command/WorkerCommand.php
$client = new SimpleClient($testConfig, $logger);
        /** @psalm-suppress InvalidArgument */
$client->bindTopic((string)$args->getOption('queue'), $processor, $args->getOption('processor'));

//  vendor/cakephp/queue/src/QueueManager.php

static::$_clients[$name] = new SimpleClient($testConfig, $logger);

```

Leaving everything as default is fine because the processing instructions are embedded in each job so no problems really.

But this seems like it will need looking at if multiple tubes / job queues will be available with the beanstalk: transport. 

My apologies for not submitting a patch but my debugging skills have stretched to their limit to get this far and I can't figure out how to fix it without breaking it.

#59

**Comment by markstory** [comment]
Passing the entire configuration array to Enqueue's SimpleClient could be ok. I'm familiar with how all the various transport adapters will work with that though. Do you know if the beanstalk adapter can have the queue name and other connection settings defined in the `url` key? Based on https://github.com/php-enqueue/enqueue-dev/blob/2e5c41c0fa8ad96e8b6bebc01b6686b41a65f4be/pkg/simple-client/SimpleClient.php#L71-L77 it looks like it would be possible.

**Comment by toggenation** [comment]
Thanks I saw this but didn't notice any examples in the php enqueue docs. But will have a deeper look at this. Would be good to be able to pass it all on an encoded url key.

**Comment by toggenation** [comment]
Okay checked and there is code to pass extra settings via the DSN but there doesn't appear to be any code in the enqueue/pheanstalk code to be able to set further options such as the beanstalk tube from the dsn. 

Seems like the only way is passing a configuration array into the SimpleClient constructor.

**Comment by doshu** [comment]
I confirm the same behavior with redis. If you don't specify in the url config "router_topic", "router_queue" and "default_queue" params, is not possible to use more than one queue.
If you don't specify them, every job is pushed on the same "enqueue.app.default" topic, and if a worker listening for job on queue A receives a message of the queue B, the consumer discard and delete the message.

A simple workaround can be the Cake Queue manager set this configuration under the hood, based on the queue name

**Comment by markstory** [comment]
Having the QueueManager set the `router_topic`, `router_queue`, and `default_queue` based on the `Queue.$name.queue` configuration value would be a nice improvement if someone wants to put a pull request together.

**Comment by CriztianiX** [comment]
> I am using the beanstalk: transport. If I specify a custom config Queue.beanstalkd.* as below this has no effect on the tube / job queue created in beanstalk when I specify the [ 'config' => 'beanstalk' ] options to ->push on a QueueManager or Queue enabled Mailer instance
> 
> ![image](https://user-images.githubusercontent.com/4483692/117101008-975d6480-adb8-11eb-9884-eb41a30ed5ec.png)
> 
> ```
>  'Queue' => [
>         'default' => [
>             // A DSN for your configured backend. default: null
>             'url' => 'beanstalk:',
> 
>             // The queue that will be used for sending messages. default: default
>             // This can be overriden when queuing or processing messages
>             'queue' => 'default',
> 
>             // The name of a configured logger, default: null
>             'logger' => null,
> 
>             // The name of an event listener class to associate with the worker
>             'listener' => \App\Listener\WorkerListener::class,
>         ],
>         'beanstalk' => [
> 
>             // A DSN for your configured backend. default: null
>             'url' => 'beanstalk:',
> 
>             // The queue that will be used for sending messages. default: default
>             // This can be overriden when queuing or processing messages
>             'queue' => 'tube1',
> 
>             // The name of a configured logger, default: null
>             'logger' => 'stdout',
> 
>             // The name of an event listener class to associate with the worker
>             'listener' => \App\Listener\WorkerListener::class,
>         ],
>     ],
> ```
> 
> I think this is because SimpleClient is instantiated with only $url = "beanstalk:"
> 
> ```
> //vendor/cakephp/queue/src/Command/WorkerCommand.php
> $url = Configure::read(sprintf('Queue.%s.url', $config));
> $client = new SimpleClient($url, $logger);
>         /** @psalm-suppress InvalidArgument */
> $client->bindTopic((string)$args->getOption('queue'), $processor, $args->getOption('processor'));
> 
> //  vendor/cakephp/queue/src/QueueManager.php
> 
> static::$_clients[$name] = new SimpleClient($config['url'], $logger);
> ```
> 
> I have tested it with passing a configuration array to each instantiation of SimpleClient and it creates the custom queue.
> 
> ![image](https://user-images.githubusercontent.com/4483692/117102864-87478400-adbc-11eb-9b72-973a1bf7aa58.png)
> 
> ```
> $testConfig = [
>         'transport' => 'beanstalk:',
>         'client' =>
>         [
>             'prefix'                   => 'enqueue',
>             'separator'                => '.',
>             'app_name'                 => 'app',
>             'router_topic'             => 'q1',
>             'router_queue'             => 'q1',
>             'default_queue'            => 'q1',
>         ],
>         'extensions' => [
>             'signal_extension' => false,
>             'reply_extension' => false,
>         ]
>     ];
> 
> //vendor/cakephp/queue/src/Command/WorkerCommand.php
> $client = new SimpleClient($testConfig, $logger);
>         /** @psalm-suppress InvalidArgument */
> $client->bindTopic((string)$args->getOption('queue'), $processor, $args->getOption('processor'));
> 
> //  vendor/cakephp/queue/src/QueueManager.php
> 
> static::$_clients[$name] = new SimpleClient($testConfig, $logger);
> ```
> 
> Leaving everything as default is fine because the processing instructions are embedded in each job so no problems really.
> 
> But this seems like it will need looking at if multiple tubes / job queues will be available with the beanstalk: transport.
> 
> My apologies for not submitting a patch but my debugging skills have stretched to their limit to get this far and I can't figure out how to fix it without breaking it.
> 
> #59

I have the same issue trying to use SQS as transport.

**Comment by ADmad** [comment]
@CriztianiX A pull request to address this issue is already open, so you can review that instead of +1ing this issue :).
