### ISSUE TITLE
Using a Queue Transport instead of push method for sending emails

### ISSUE THREAD

**Issue by doshu** [cakephp/queue#64]
instead using the push method of the QueueTrait, a Queue Transport should be created.
This will allow using the standard send method of the mailer class.
This will give the ability to swapping the current method of sending emails in the application, without rewrite code.

**Comment by markstory** [comment]
Having a mail transport that creates queue jobs is a neat idea.

**Comment by jeremyharris** [comment]
A while ago I proposed (to the original repo) a way to queue Cake events, which is more inclusive than just emails. Here's a post about it: https://someguyjeremy.com/2017/07/queued-events-in-cakephp.html

I've been using that method to queue events for a while (for emails, pdf generation, api requests, etc.) and it works really nicely and I don't have to write a lot of extra code - just a listener. Perhaps a solution like that could fit in cakephp/queue?

**Comment by doshu** [comment]
Background event handling is another topic in my opinion.
Sending an email is not an event.

However, the idea of introducing a global way to dispatch event in
background is good. Other frameworks like laravel already do that.
The logic is embedded into the event dispatcher that if the event listener
is marked as a "background task", the event manager queue its execution,
instead execute it in realtime.

Il giorno ven 16 lug 2021 alle ore 16:47 Jeremy Harris <
***@***.***> ha scritto:
