### ISSUE TITLE
[RFC] DIC support

### ISSUE THREAD

**Issue by robertpustulka** [cakephp/queue#66]
Are there any plans for adding DIC support? I would love to be able to get the queue JobInterface instances from a container. My jobs have a few dependencies that need to be pulled from a DIC. Now I'm using a workaround with a global DIC locator, but that's not ideal of course.

I'm not very familiar with the plugin internals yet, but it seems that the job is build in a Message class and returned as a callable so the Message should have access to the container instance somehow (from a Processor instance?)

I'd be happy to work on a PR, but need some direction on how to approach this.

**Comment by markstory** [comment]
> Are there any plans for adding DIC support? I would love to be able to get the queue JobInterface instances from a container. My jobs have a few dependencies that need to be pulled from a DIC.

Not currently, but I don't think anyone is focusing on this plugin right now.

> I'm not very familiar with the plugin internals yet, but it seems that the job is build in a Message class and returned as a callable so the Message should have access to the container instance somehow (from a Processor instance?)

Jobs and Messages are created by the [Processor](https://github.com/cakephp/queue/blob/master/src/Queue/Processor.php) so if we can get the container into there than we should be able to use it to create Job instances using the container.

**Comment by robertpustulka** [comment]
Thanks @markstory. I'm planning to play around with it a bit and hopefully come up with a PR.

**Comment by LordSimal** [comment]
This feature was added in https://github.com/cakephp/queue/pull/109 so I will close this issue
