### ISSUE TITLE
RFC - Remove event queuing

### ISSUE THREAD

**Issue by markstory** [cakephp/queue#8]
Currently this plugin can queue 'jobs' or 'events'. This adds surface area to the plugin for handling events and the use cases around queuing events are not entirely clear.

I'm proposing we remove the ability to queue events and instead focus solely on queuing jobs. By focusing on jobs we could also simplify the `QueueManager::push()` interface and only requires the classname + arguments.

**Comment by jeremyharris** [comment]
When I proposed this it was for my use case. I find it makes sense to queue the event and let it be dispatched to the event manager when the job is processed. This makes writing job handlers the same as writing event listeners. No need to have code to handle the job when it's processed - the event system does that.

However looking at how it was written it isn't in that spirit, but instead triggers an "execute" method on the event class which feels strange. Perhaps I didn't get my point across.

I agree that if that's how the "queuing events" feature is to be executed it makes little sense and should be removed.

**Comment by josegonzalez** [comment]
@jeremyharris thats only for Jobs, but events get triggered as normal via the [EventJob](https://github.com/cakephp/queue/blob/master/src/Job/EventJob.php#L41).

That said, I am not fond of queueing events, so I'm fine with removing this or refactoring how it should look if there is a better implementation.

**Comment by jeremyharris** [comment]
@josegonzalez ah thanks for pointing that out, I misread the class.

If queuing events doesn't make sense to people and goes away, that's fine :) just wanted to share my experiences while we were talking about it.

**Comment by josegonzalez** [comment]
I just personally think it's weird to queue an event and then have to hunt for the listener/handler in the Application class. Looking for a job class makes things quite clear :)
