### ISSUE TITLE
RFC - Rename project

### ISSUE THREAD

**Issue by markstory** [cakephp/queue#9]
A few folks in the cakephp-dev channel have commented that the `queue` name is a bit generic and results in the project having classnames with multiple instances of the same word e.g `Queue\Queue\QueueExtension`.

I'd like to discuss some alternate names that we could use. The goal of the rename would be to better communicate the problem or solution space of the plugin and be less literal about the underlying technology used.

Given that the plugin is going to focus on background jobs and delayed/deferred task execution, some candidates are:

* Batch
* Backburner
* Deferred
* Workline
* Later
* DelayedJob
* JobRunner
* Tasker

**Comment by ADmad** [comment]
`Deferred` was also suggested as an option.

**Comment by Megslalk** [comment]
So many cool suggestions! +1 for Backburner

**Comment by dakota** [comment]
+1 for Batch

and

+1/2 for Backburner :)

**Comment by rchavik** [comment]
Procastinator :smile:

**Comment by skie** [comment]
Async

**Comment by diegosardina** [comment]
+1 for Batch

Queues are sometimes called _Batch queues_, so Batch\Queue makes sense for me

**Comment by dereuromark** [comment]
I would go simple and use the same pattern for core modules like
https://github.com/cakephp/elastic-search/blob/master/composer.json#L31, so `Cake/Queue` as plugin name. Simple and effective.

    Cake\Queue\Queue\QueueExtension

Wouldnt be too bad as namespace. Maybe also the internal Queue namespace could be made more specific instead? Like `Enqueue`, following the name the extension class also comes from.

    Cake\Queue\Enqueue\EnqueueExtension

**Comment by skie** [comment]
In fact queues implements asyncronous calls pattern. So I dont understand negative reaction about Async idea, at least i more talkaive then Deffered.

**Comment by dereuromark** [comment]
> In fact queues implements asyncronous calls pattern. So I dont understand negative reaction about Async idea, at least i more talkaive then Deffered.

When reading about the semantic difference:

> The difference between async and defer centers around when the script is executed. Each async script executes at the first opportunity after it is finished downloading and before the window's load event. ... Whereas the defer scripts, on the other hand, are guaranteed to be executed in the order they occur in the page.

Similar things could be said about a queue: The tasks are all async, true.
But maybe deferred is a more specific meaning as in: not random, but as first-in first-out kind of priority queue. But I don't know enough about the implementation of this specific queue to say this is true here. And that you can give priorities or assert certain exec orders.

**Comment by rochamarcelo** [comment]
Cake\Queue is a direct and clear namespace, this avoid multiple instances of the same word, which seems to be the main issue.

**Comment by rochamarcelo** [comment]
Based on the suggested list +1 for Batch

**Comment by celsowm** [comment]
Empilhadeira

**Comment by davidyell** [comment]
I like Backburner <3

**Comment by akkaweb** [comment]
Echeleon

**Comment by jeremyharris** [comment]
Queue is fine for me, but if we have to change it I like DelayedJob and JobRunner.

**Comment by josegonzalez** [comment]
I really don't want to make up a funky name. I've had enough of that in the past - I've even created a few bad plugin names myself - and it confuses what exactly the code is supposed to do. None of the official plugins have a "fun" name, so we shouldn't try to do that here either.

That said, if folks want a new name, thats also fine with me.

**Comment by LuizMarin** [comment]
leaving in 'Backburner' expresses the idea well in Portuguese.

**Comment by markstory** [comment]
> Cake\Queue\Queue\QueueExtension

This is a class I would like to rename if we keep `Queue` in the package name. The same word appearing three times in a row bothers me.

> None of the official plugins have a "fun" name, so we shouldn't try to do that here either.

What about bake, and debugkit :smile:

**Comment by delamux** [comment]
TaskDispenser

**Comment by josegonzalez** [comment]
@markstory those are grandfathered in :P

- `Queue\Queue\QueueExtension`: Could probably be split into `Queue\Consumption\MaxIterationsExtension` and `Queue\Consumption\MaxRuntimeExtension` (Consumption is the higher-level namespace upstream)

**Comment by EliW** [comment]
Surprised there are few suggestions that stay on theme.  

Baker
Bakery
Conveyer
Conveyerized
Mixer
Oven

Not saying any/all of those are good.  But they are fun and play with the Cake theme.  And can all be justified to mean queue / ‘taking steps’ / ‘doing things in sequence’

**Comment by ADmad** [comment]
Fun name: BackBurner
Not fun, not boring name: Deferred
Boring but functional and descriptive name: JobQueue/JobRunner

**Comment by butaevg** [comment]
Tasker - short and clear.

**Comment by josbeir** [comment]
I vote Async or Deferred or just use a derivative of Queue like Enqueue as mentioned above.

As this will be an official library a fancy name like BackBurner is too non-descriptive and a bit lame tbh ;-)

**Comment by Tiborhajos** [comment]
I also strongly prefer a functional name above a fun name, as the latter obfuscates meaning.

Personally I see nothing wrong with Queue, as that is exactly what it is. Perhaps it could be `Enqueue` after the name of the extension.

If I absolutely have to pick from the provided options, I would go with @ADmad 's improvement of JobRunner: JobQueue/JobRunner

**Comment by Zwartpet** [comment]
Functional names are for people who can't read code/documentation :D 
**Cake/Layers**

**Comment by Tiborhajos** [comment]
@Zwartpet I see what you did there 😄

**Comment by markstory** [comment]
I like 'Conveyer'. It helps communicate that we're moving work somewhere else and hits a good balance of fun and literal.

My concern with Async/deferred is that those terms have very clear meanings in adjacent technologies. They are used in Javascript, python and golang to mean something quite different than what this code does.

**Comment by ADmad** [comment]
`Cake\Conveyor` works for me.

**Comment by josegonzalez** [comment]
I don't know that seeing "Conveyer" on the sidebar in the docs will tell me enough to know that Cake supports queuing.

**Comment by ADmad** [comment]
Seeing just "queue" doesn't tell you either that it's a job queue. There are other queues too, for eg. the middleware queue.

**Comment by burzum** [comment]
Please something simple and clear that expresses what it is:

* Cake\Queue
* Cake\JobQueue

Especially names like "async" and "deffered" make me think it's a promise / async library but clearly not a queue.
