### ISSUE TITLE
RFC - Queue Name in Payload

### ISSUE THREAD

**Issue by amayer5125** [cakephp/queue#90]
Should the [queue name](https://github.com/cakephp/queue/blob/c5536b5ae576d0af2d37c5a14f65033c0ff3e5e5/src/QueueManager.php#L219) be in the payload? I know most people probably aren't approaching the limit of their queue message size, but I don't think this information needs to be there. We don't use it anywhere in the plugin so removing it wouldn't hurt anything.

**Comment by markstory** [comment]
I don't think that key is used by enqueue either so it should be relatively safe to scrap in a backwards compatible way.
